[project]
name = "ft4ftir"
version = "0.1.1"
authors = [
    {name = "Jon Gabirondo-López", email = "jon.gabirondol@ehu.eus"},
    {name = "Iñigo González de Arrieta", email = "inigo.gonzalezdearrieta@ehu.eus"}
    ]
description="A package for processing FTIR interferograms."
url="https://github.com/jongablop/ft4ftir",
requires-python = ">=3.7"
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "brukeropusreader>=1.3.0"
    ]
license = "GPL-3.0-or-later"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
